=== Cheps-s/http-BasicWebdeveloperPortfolio/src/Animation website/html/css/sample.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rss">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="channel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" />
                            <xs:element name="link" type="xs:string" />
                            <xs:element name="description" type="xs:string" />
                            <xs:element name="language" type="xs:string" />
                            <xs:element name="item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string" />
                                        <xs:element name="link" type="xs:string" />
                                        <xs:element name="description" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Cheps-s/http-BasicWebdeveloperPortfolio/src/Animation website/html/css/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="sample.xsd">
    <channel>
        <title>RSS title</title>
        <link> https://mywebsitename/index.html </link>
        <description>My Blog</description>
        <language>en</language>
        <item>
            <title>Coding the Financial Market</title>
            <link>
https://www.geeksforgeeks.org/finance/coding-the-financial-market/
           </link>
            <description>Financial engineering is formulated and framed 
              with the concepts from
            , Applied Mathematics, Computer Science Engineering, Statistics,
            Probability principles and Economic theory.
             the functionnalities of the finacial market are code by engineers and programmers. The financial market is a place where buyers and sellers interact to trade financial assets such as stocks, bonds, commodities, and currencies. The
           
            </description>
        </item>
        <item>
            <title>Flutter Architecture Application</title>
            <link>
https://www.geeksforgeeks.org/flutter/flutter-architecture-application/
            </link>
            <description>
             Flutter application consists of widgets,
             Gestures,Concept of state,layers
             Widgets are the primary component of any
             flutter application. It acts as a UI for 
             the user to interact with the application.
             Any flutter application is itself a widget 
             that is made up of a combination of widgets.
             In a standard application, the root defines 
             the structure of the application followed by
             a Material App widget which basically holds 
             its internal components in place. This is 
             where the properties of the UI and the application
             itself is set. The Material App has a Scaffold widget
             that consists of the visible components (widgets) of
             the application.
            </description>
        </item>
        <item>
            <title>Cool Technology Facts</title>
            <link>
https://www.geeksforgeeks.org/cool-technology-facts/
            </link>
            <description>
              The incredible advancement has been made by 
              the technology over the past 20 years.
              Here are some quirky facts about technology
              that may be surprising for you :
              30th November is known as “Computer Security Day“.
              Although GPS is free to use for the world but it 
              costs $2 million per day to operate. The
              money comes from the American tax revenue.

            </description>
        </item>
        <item>
            <title>Introduction to WebRTC</title>
            <link>
https://www.geeksforgeeks.org/techtips/introduction-to-webrtc/
            </link>
            <description>
              It is an open source and free project 
              that used to provide real-time 
              communication to mobile applications and web browsers 
              WebRTC stands for Web Real-Time Communication. 
            </description>
        </item>
    </channel>
</rss>
